# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Kwiki-OpenSearch-Service
version:      0.02
version_from: lib/Kwiki/OpenSearch/Service.pm
installdirs:  site
requires:
    Kwiki:                         0.37
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
